"""
Earnings Briefing TTS Audio Generator.
Generates an MP3 audio file from the Beiersdorf earnings TTS script.

Uses `edge-tts` for fast, free, high-quality neural voices.
Voice: de-DE-KillianNeural (Killian, German)

Usage:
    pip install edge-tts
    python generate_audio.py
    # → Outputs: beiersdorf_q4_fy2025_briefing.mp3

Optional:
    python generate_audio.py --voice de-DE-ConradNeural
    python generate_audio.py --output my_custom_name.mp3
    python generate_audio.py --script path/to/other_script.md
"""
import asyncio
import argparse
import os
import re
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:
    print("❌ edge-tts not installed. Run: pip install edge-tts")
    sys.exit(1)


# ── Voice Registry ──────────────────────────────────────────────────────────
VOICES = {
    "christopher": "en-US-ChristopherNeural", # English male (Primary)
    "jenny": "en-US-JennyNeural",           # English female
    "killian": "de-DE-KillianNeural",      # German male
    "katja": "de-DE-KatjaNeural",           # German female
}

# ── Defaults ─────────────────────────────────────────────────────────────────
DEFAULT_VOICE = "en-US-ChristopherNeural"
DEFAULT_RATE = "+0%"         # Normal speed. Use "+10%" for faster, "-10%" for slower
DEFAULT_VOLUME = "+0%"       # Normal volume
DEFAULT_PITCH = "+0Hz"       # Normal pitch

# ── Kasona Branding ────────────────────────────────────────────────────────
# English
KASONA_INTRO_EN = "This quarterly earnings review of {company_name} shows the latest fundamental developments, future outlook, and market reactions. We provide this analysis to give you a clear sense of the company's current state and what to expect in the coming periods."
KASONA_CONTENT_EN = """
[INSTITUTIONAL METADATA]
Ticker: {ticker_eod}
Fiscal Period: {fiscal_period}
Impact Score: {impact_score}
PDF Report: {pdf_url}
Audio Briefing: {audio_url}
"""
KASONA_OUTRO_EN = "That was a Kasona production. Check out our full offering and additional research at Kasona.ai. We distill the most relevant market insights using our AI-driven analysis specifically for your portfolio. This does not constitute financial advice, buy or sell recommendations, and you are in the driver's seat with your money decisions. Feel free to read our disclaimer. Until next time!"

# German
KASONA_INTRO_DE = "Diese Quartalsergebnis-Analyse von {company_name} zeigt die neuesten fundamentalen Entwicklungen, den Zukunftsausblick und die Marktreaktionen. Wir bieten dieses Update an, um Ihnen einen klaren Überblick über den aktuellen Zustand des Unternehmens zu geben."
KASONA_CONTENT_DE = """
[INSTITUTIONELLE METADATEN]
Ticker: {ticker_eod}
Berichtszeitraum: {fiscal_period}
Impact Score: {impact_score}
PDF-Bericht: {pdf_url}
Audio-Briefing: {audio_url}
"""
KASONA_OUTRO_DE = "Das war eine Kasona-Produktion. Besuchen Sie Kasona.ai, um unser vollständiges Angebot an Analysen für Ihr Portfolio zu entdecken. Wir bereiten die relevantesten Markteinblicke mit unserer KI-gestützten Analyse speziell für Ihr Portfolio auf. Dies stellt keine Finanzberatung oder Kauf- bzw. Verkaufsempfehlung dar. Sie behalten die volle Kontrolle über Ihre Anlageentscheidungen. Lesen Sie dazu auch unseren Disclaimer. Bis zum nächsten Mal!"

# ── Internal Metadata Keywords (NEVER spoken aloud) ──────────────────
INTERNAL_KEYWORDS = [
    "rule of 3", "rule of three", "word count", "generated by kasona",
    "eodhd", "python", "disclaimer:", "tts script", "audio script",
    "kasona institutional analytics", "recommendation:", "empfehlung:",
]


def enforce_rule_of_three(text: str) -> str:
    """
    Enforces the 'Rule of 3': Limits the number of figures in a single paragraph 
    to avoid listener cognitive overload.
    """
    paragraphs = text.split("\n\n")
    cleaned_paragraphs = []
    
    # Simple regex to find numbers (including $ and %)
    num_pattern = re.compile(r'\$?\d+(?:\.\d+)?%?')
    
    for p in paragraphs:
        tokens = p.split()
        count = 0
        new_tokens = []
        for token in tokens:
            if num_pattern.search(token):
                if count < 3:
                    new_tokens.append(token)
                    count += 1
                else:
                    # Replace with a qualitative lead or just skip
                    continue 
            else:
                new_tokens.append(token)
        cleaned_paragraphs.append(" ".join(new_tokens))
    
    return "\n\n".join(cleaned_paragraphs)


def clean_markdown_for_speech(text: str) -> str:
    """
    Strips markdown formatting and non-spoken characters for a clean TTS experience.
    """
    # 1. Strip bold and italic
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    
    # 2. Strip inline code
    text = re.sub(r'`(.*?)`', r'\1', text)
    
    # 3. Strip hyperlinks: [label](url) -> label
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    
    # 4. Strip raw URLs (http/https/www)
    text = re.sub(r'https?://\S+', '', text)
    text = re.sub(r'www\.\S+', '', text)
    
    # 5. Remove forward and back slashes (to avoid "slash" being spoken)
    # But keep them if they are parts of dates (e.g. 12/24) - actually, for TTS, 
    # "12 24" is often better. Let's just remove them.
    text = text.replace("/", " ").replace("\\", " ")
    
    # 6. Remove structural symbols and markdown table remnants
    text = text.replace("#", "").replace("|", " ").replace("---", " ").replace("___", " ")
    text = text.replace("_", " ")
    
    # 7. Remove stylistic markers (e.g., [serious], [analytical], [newscaster])
    # But keep [pause] tags as they are processed later
    text = re.sub(r'\[(?!pause)(.*?)\]', '', text)
    
    # 8. Remove leading bullet points (e.g., - , * , + )
    text = re.sub(r'^[ \t]*[-*+][ \t]+', '', text)
    
    # 9. Normalize horizontal whitespace (tabs/spaces) but preserve newlines
    text = re.sub(r'[ \t]+', ' ', text)
    
    # 10. Normalize multi-newlines to stay clean but distinct
    text = re.sub(r'\n\s*\n', '\n\n', text)
    
    return text.strip()

    return text.strip()


def build_market_reaction_segment(
    company_name: str,
    move_7d: float | None,
    move_post: float | None,
    benchmark_label: str | None,
    benchmark_move_post: float | None,
    relative_perf: float | None,
    is_german: bool = False,
) -> str:
    """
    Builds a spoken market reaction paragraph covering:
    - 7-day pre-earnings drift and what it signals
    - Post-earnings reaction and market-participant rationale
    - Benchmark comparison (Nasdaq-100 or S&P 500)
    Returns empty string if no movement data is available.
    """
    if move_7d is None and move_post is None:
        return ""

    parts = []

    if is_german:
        parts.append("Bevor wir zum Abschluss kommen, werfen wir einen Blick auf die Marktreaktion rund um die Berichterstattung.")
    else:
        parts.append("Before we close, let's look at how the market responded around the earnings release.")

    # Pre-earnings drift
    if move_7d is not None:
        if move_7d > 3.0:
            drift_sent = f"In the seven trading days leading up to the announcement, {company_name} shares gained {move_7d:.1f} percent. This kind of pre-earnings appreciation typically reflects bullish positioning ahead of an expected beat, or sector momentum carrying the name higher."
        elif move_7d > 1.5:
            drift_sent = f"In the seven trading days leading up to the announcement, {company_name} shares gained {move_7d:.1f} percent, suggesting measured constructive positioning ahead of results."
        elif move_7d < -3.0:
            drift_sent = f"In the seven trading days leading up to the announcement, {company_name} shares declined {abs(move_7d):.1f} percent — indicating defensive repositioning or active short selling by participants anticipating a miss."
        elif move_7d < -1.5:
            drift_sent = f"In the seven trading days leading up to the announcement, shares declined {abs(move_7d):.1f} percent, reflecting cautious positioning ahead of the release."
        else:
            drift_sent = f"In the seven trading days leading up to the announcement, {company_name} shares were largely flat, at {move_7d:+.1f} percent. This balanced positioning suggests the market entered the event without a strong directional lean."
        parts.append(drift_sent)

    # Post-earnings reaction
    if move_post is not None:
        if move_post > 5.0:
            react_sent = f"On the day following the earnings release, shares surged {move_post:.1f} percent. A move of that scale typically signals results exceeded not just consensus but likely the more optimistic whisper numbers, triggering short covering and fresh momentum buying."
        elif move_post > 2.0:
            react_sent = f"The day following the release saw shares rise {move_post:.1f} percent — a measured positive reaction consistent with results that cleared the consensus bar without dramatically exceeding expectations."
        elif move_post > 0.5:
            react_sent = f"Following the announcement, shares edged up {move_post:.1f} percent. The muted gain suggests results met expectations after any pre-announcement appreciation had already absorbed some of the upside."
        elif move_post < -5.0:
            react_sent = f"On the day following the release, shares fell sharply by {abs(move_post):.1f} percent. A decline of that magnitude typically signals a material negative surprise — whether from the headline number, a guidance cut, or margin deterioration that undermined the prevailing growth story."
        elif move_post < -2.0:
            react_sent = f"Following the announcement, shares declined {abs(move_post):.1f} percent. This reaction suggests results disappointed relative to consensus or that forward guidance introduced uncertainty, with event-driven participants likely driving the initial leg lower."
        elif move_post < -0.5:
            react_sent = f"Shares dipped {abs(move_post):.1f} percent following the announcement — a modest negative reaction possibly reflecting a slight miss on one metric or a cautious tone from management on the outlook."
        else:
            react_sent = f"Shares were essentially unchanged following the announcement, moving just {move_post:+.1f} percent. A flat post-earnings reaction typically means results broadly matched expectations, leaving the market without a strong new signal to act on."
        parts.append(react_sent)

    # Benchmark comparison
    if benchmark_move_post is not None and relative_perf is not None and benchmark_label:
        direction = "outperformed" if relative_perf > 0 else "underperformed"
        abs_rel = abs(relative_perf)
        if abs_rel > 3.0:
            rel_note = f"a divergence of {abs_rel:.1f} percentage points over a single session reflects strong company-specific catalysts rather than broader market momentum"
        elif abs_rel > 1.0:
            rel_note = f"a {abs_rel:.1f} percentage point spread indicates a meaningful company-specific move relative to the prevailing market environment"
        else:
            rel_note = "near-benchmark performance suggests broader market conditions contributed materially to the day's price action"
        bm_sent = (
            f"For broader context, the {benchmark_label} moved {benchmark_move_post:+.2f} percent "
            f"over the same post-earnings window. {company_name} {direction} its benchmark by "
            f"{abs_rel:.1f} percentage points — {rel_note}."
        )
        parts.append(bm_sent)

    return "  ".join(parts)


def extract_tts_text(script_path: str, metadata: dict = {}, voice: str = DEFAULT_VOICE) -> tuple[str, str]:
    """
    Reads a TTS script markdown file and extracts both:
    1. The AUDIT SCRIPT (with metadata/URLs preserved)
    2. The SPOKEN TEXT (cleaned for TTS)
    
    Returns: (audit_script, spoken_text)
    """
    # Detect language from voice
    is_german = "de-DE" in voice
    intro_tmpl = KASONA_INTRO_DE if is_german else KASONA_INTRO_EN
    outro_tmpl = KASONA_OUTRO_DE if is_german else KASONA_OUTRO_EN
    content_tmpl = KASONA_CONTENT_DE if is_german else KASONA_CONTENT_EN

    with open(script_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    raw_spoken_lines = []
    
    in_frontmatter = False
    frontmatter_closed = False

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Skip YAML frontmatter
        if i == 0 and stripped == "---":
            in_frontmatter = True
            continue
        if in_frontmatter and not frontmatter_closed:
            if stripped == "---":
                frontmatter_closed = True
            continue

        # Keep headers but clean them later
        if stripped.startswith("#"):
            raw_spoken_lines.append(stripped)
            continue
            
        if stripped == "---" or stripped.startswith(">"):
            continue

        # Handle tables (lines with multiples |)
        # Convert them to a spoken-friendly list format
        if stripped.count("|") > 1:
            # Skip the separator line (--- | ---)
            if re.match(r'^[ \t]*[:\- \t\|]+$', stripped):
                continue
            
            # Clean the row: | Metric | Value | -> "Metric, Value"
            cells = [c.strip() for c in stripped.split("|") if c.strip()]
            if cells:
                raw_spoken_lines.append(", ".join(cells) + ".")
            continue

        # Skip empty bullet points
        if stripped == "-" or stripped == "*" or stripped == "+":
            continue

        # Skip empty lines but preserve paragraph breaks
        if not stripped:
            if raw_spoken_lines and raw_spoken_lines[-1] != "":
                raw_spoken_lines.append("")
            continue

        raw_spoken_lines.append(stripped)

    # Base body for both
    raw_body = "\n".join(raw_spoken_lines).strip()
    
    # Metadata for formatting
    meta_defaults = {
        "ticker_eod": metadata.get("ticker_eod", "N/A"),
        "company_name": metadata.get("company_name", "the specified company"),
        "fiscal_period": metadata.get("fiscal_period", "N/A"),
        "impact_score": metadata.get("impact_score", "N/A"),
        "pdf_url": metadata.get("pdf_url", "N/A"),
        "audio_url": metadata.get("audio_url", "N/A"),
    }
    
    # 1. Generate Audit Script (Rich with metadata)
    audit_intro = intro_tmpl.format(**meta_defaults)
    audit_content = content_tmpl.format(**meta_defaults) if content_tmpl else ""
    audit_outro = outro_tmpl.format(**meta_defaults)
    
    # Build market reaction segment from structured metadata (not from markdown)
    market_reaction = build_market_reaction_segment(
        company_name=meta_defaults["company_name"],
        move_7d=metadata.get("move_7d"),
        move_post=metadata.get("move_post"),
        benchmark_label=metadata.get("benchmark_label"),
        benchmark_move_post=metadata.get("benchmark_move_post"),
        relative_perf=metadata.get("relative_perf"),
        is_german=is_german,
    )

    audit_script = f"{audit_intro}\n\n{audit_content}\n\n{raw_body}\n\n{market_reaction}\n\n{audit_outro}"

    # 2. Generate Spoken Text (Cleaned for TTS)
    spoken_intro = clean_markdown_for_speech(audit_intro)
    spoken_content = clean_markdown_for_speech(audit_content)
    spoken_body = clean_markdown_for_speech(raw_body)
    spoken_market = clean_markdown_for_speech(market_reaction)
    spoken_outro = clean_markdown_for_speech(audit_outro)

    spoken_parts = [spoken_intro]
    if spoken_content: spoken_parts.append(spoken_content)
    spoken_parts.append(spoken_body)
    if spoken_market: spoken_parts.append(spoken_market)
    spoken_parts.append(spoken_outro)
    
    spoken_text = "\n\n".join(spoken_parts)

    # Hard sanitize: remove any remaining internal keywords from both
    def hard_sanitize(txt):
        clean_lines = []
        for line in txt.split("\n"):
            lower = line.lower()
            if any(kw in lower for kw in INTERNAL_KEYWORDS):
                continue
            clean_lines.append(line)
        res = "\n".join(clean_lines)
        while "\n\n\n" in res:
            res = res.replace("\n\n\n", "\n\n")
        return res.strip()

    return hard_sanitize(audit_script), hard_sanitize(spoken_text)


async def generate_audio_ssml(
    ssml: str,
    output_path: str,
    voice: str = DEFAULT_VOICE,
    rate: str = DEFAULT_RATE,
    volume: str = DEFAULT_VOLUME,
    pitch: str = DEFAULT_PITCH,
) -> str:
    """
    Generate MP3 audio from SSML using edge-tts.
    """
    communicate = edge_tts.Communicate(
        text=ssml,  # Passing SSML directly in text field works if it starts with <speak>
        voice=voice,
        rate=rate,
        volume=volume,
        pitch=pitch,
    )

    print(f"[*] Generating audio with voice: {voice}")
    print(f"[*] SSML length: {len(ssml)} characters")
    print(f"[*] Applied Rate: {rate}")
    print(f"[*] Output: {output_path}")

    await communicate.save(output_path)

    file_size = os.path.getsize(output_path)
    print(f"[OK] Audio generated successfully!")
    print(f"[OK] File size: {file_size / 1024 / 1024:.1f} MB")

    return os.path.abspath(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Generate TTS audio from an earnings briefing script"
    )
    parser.add_argument(
        "--script",
        default=os.path.join(os.path.dirname(__file__), "beiersdorf_q4_fy2025_tts_script.md"),
        help="Path to the TTS script markdown file",
    )
    parser.add_argument(
        "--company",
        default="Target Company",
        help="Company name for branding intro",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(__file__), "beiersdorf_q4_fy2025_briefing.mp3"),
        help="Output MP3 file path",
    )
    parser.add_argument(
        "--voice",
        default=DEFAULT_VOICE,
        help=f"TTS voice (default: {DEFAULT_VOICE}). Options: {', '.join(VOICES.keys())}",
    )
    parser.add_argument(
        "--rate",
        default=DEFAULT_RATE,
        help="Speech rate (e.g., '+10%%', '-5%%')",
    )
    parser.add_argument(
        "--ticker-eod",
        help="Ticker EOD (e.g., AMZN.NASDAQ)",
    )
    parser.add_argument(
        "--fiscal-period",
        help="Fiscal period (e.g., Q4 2025)",
    )
    parser.add_argument(
        "--impact-score",
        help="Impact score (0-100)",
    )
    parser.add_argument(
        "--pdf-url",
        help="Public URL for the PDF report",
    )
    parser.add_argument(
        "--audio-url",
        help="Public URL for the Audio briefing",
    )
    parser.add_argument(
        "--move-7d",
        type=float,
        default=None,
        help="Stock % change 7 trading days prior to earnings (e.g. 2.3)",
    )
    parser.add_argument(
        "--move-post",
        type=float,
        default=None,
        help="Stock % change day after earnings (e.g. -1.5)",
    )
    parser.add_argument(
        "--benchmark-label",
        default=None,
        help="Benchmark name for comparison (e.g. 'Nasdaq-100' or 'S&P 500')",
    )
    parser.add_argument(
        "--benchmark-move",
        type=float,
        default=None,
        help="Benchmark % change over post-earnings window",
    )
    parser.add_argument(
        "--relative-perf",
        type=float,
        default=None,
        help="Relative performance vs benchmark in percentage points",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated audio script and exit without generating audio",
    )
    parser.add_argument(
        "--list-voices",
        action="store_true",
        help="List available voices and exit",
    )

    args = parser.parse_args()

    # List voices
    if args.list_voices:
        print("Available preset voices:")
        for name, voice_id in VOICES.items():
            print(f"  {name:15s} → {voice_id}")
        print(f"\nUse --voice with the full voice ID or a preset name.")
        return

    # Resolve voice name
    voice = VOICES.get(args.voice.lower(), args.voice)

    # Prepare metadata
    metadata = {
        "ticker_eod": args.ticker_eod,
        "company_name": args.company,
        "fiscal_period": args.fiscal_period,
        "impact_score": args.impact_score,
        "pdf_url": args.pdf_url,
        "audio_url": args.audio_url,
        "move_7d": args.move_7d,
        "move_post": args.move_post,
        "benchmark_label": args.benchmark_label,
        "benchmark_move_post": args.benchmark_move,
        "relative_perf": args.relative_perf,
    }

    # Read and extract script
    script_path = args.script
    if not os.path.exists(script_path):
        print(f"❌ Script not found: {script_path}")
        sys.exit(1)

    print(f"[READ] Reading script: {Path(script_path).name}")
    audit_script, spoken_text = extract_tts_text(script_path, metadata=metadata, voice=voice)

    if not spoken_text:
        print("❌ No spoken text found in the script.")
        sys.exit(1)

    # Calculate target rate based on duration
    words = spoken_text.split()
    word_count = len(words)
    target_duration_s = 420  # 7 minutes
    
    # Base rate is 150 wpm
    base_wpm = 145 
    target_wpm = word_count / (target_duration_s / 60)
    rate_adjustment = int(((target_wpm / base_wpm) - 1) * 100)
    
    # Clip rate between -20% and +50% for natural sound
    rate_adjustment = max(-20, min(50, rate_adjustment))
    final_rate = f"{'+' if rate_adjustment >= 0 else ''}{rate_adjustment}%"
    
    print(f"[*] Word count: {word_count}")
    print(f"[*] Target duration: {target_duration_s}s (7m)")
    print(f"[*] Calculated Rate Adjustment: {final_rate}")

    # Process spoken text into natural paragraphs with pauses
    final_script_parts = []
    paragraphs = spoken_text.split("\n\n")
    for p in paragraphs:
        if not p.strip(): continue
        
        # Replace [pause] with qualitative punctuation
        def replace_pause(match):
            return " ... " 

        p_clean = re.sub(r'\[pause(?: duration="(.*?)")?\]', replace_pause, p)
        if p_clean[-1] not in ".!?":
            p_clean += "."
        final_script_parts.append(p_clean)
    
    final_audio_text = "  \n\n".join(final_script_parts)

    if args.dry_run:
        print("\n" + "="*40 + " AUDIT SCRIPT " + "="*40)
        print(audit_script)
        print("\n" + "="*40 + " SPOKEN TEXT (TTS) " + "="*40)
        print(final_audio_text)
        print("="*94 + "\n")
        return

    # Generate audio from clean spoken text
    async def generate():
        communicate = edge_tts.Communicate(
            text=final_audio_text,
            voice=voice,
            rate=final_rate,
        )

        print(f"[*] Generating audio with voice: {voice}")
        print(f"[*] Text length: {len(final_audio_text)} characters")
        print(f"[*] Applied Rate: {final_rate}")
        print(f"[*] Output: {args.output}")

        await communicate.save(args.output)
        
        # Save the AUDIT script (with URLs) for indexing
        script_output = Path(args.output).with_suffix(".txt")
        with open(script_output, "w", encoding="utf-8") as f:
            f.write(audit_script)
        print(f"[OK] Audit script saved: {script_output.name}")

    asyncio.run(generate())

    print(f"\n[DONE] Play with: open '{args.output}'")


if __name__ == "__main__":
    main()
